apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hello-world2
  namespace: default
spec:
  components:
  - name: hello-world2
    properties:
      cpu: "0.1"
      exposeType: ClusterIP
      image: dnxsolutions/nginx-hello
      memory: 10Mi
      ports:
      - expose: true
        port: 80
        protocol: TCP
    traits:
    - properties:
        replicas: 1
      type: scaler
    type: webservice
  policies:
  - name: default
    properties:
      clusters:
      - local
      namespace: default
    type: topology
  workflow:
    mode: {}
    steps:
    - meta:
        alias: Deploy To default
      name: default
      properties:
        policies:
        - default
      type: deploy